export const FALLBACK_VERSES = [
  { text: "O Senhor é o meu pastor; nada me faltará.", reference: "sl 23:1", book: "sl", chapter: 23, verse: 1, theme: "pastor" },
  { text: "Deus é amor; e aquele que permanece em amor permanece em Deus, e Deus nele.", reference: "1jo 4:16", book: "1jo", chapter: 4, verse: 16, theme: "amor" },
  { text: "Tudo posso naquele que me fortalece.", reference: "fp 4:13", book: "fp", chapter: 4, verse: 13, theme: "forca" },
  { text: "Buscai ao Senhor enquanto se pode achar, invocai-o enquanto está perto.", reference: "is 55:6", book: "is", chapter: 55, verse: 6, theme: "oracao" },
  { text: "Deus é o nosso refúgio e fortaleza, socorro bem presente nas tribulações.", reference: "sl 46:1", book: "sl", chapter: 46, verse: 1, theme: "conforto" },
  { text: "A alegria do Senhor é a vossa força.", reference: "ne 8:10", book: "ne", chapter: 8, verse: 10, theme: "alegria" },
  { text: "E conhecereis a verdade, e a verdade vos libertará.", reference: "jo 8:32", book: "jo", chapter: 8, verse: 32, theme: "sabedoria" },
  { text: "Respondeu Jesus: Eu sou o caminho, e a verdade, e a vida.", reference: "jo 14:6", book: "jo", chapter: 14, verse: 6, theme: "caminho" },
  { text: "Vinde a mim, todos os que estais cansados e sobrecarregados, e eu vos aliviarei.", reference: "mt 11:28", book: "mt", chapter: 11, verse: 28, theme: "conforto" },
  { text: "O amor é paciente, é benigno; o amor não arde em ciúmes, não se ufana, não se ensoberbece.", reference: "1co 13:4", book: "1co", chapter: 13, verse: 4, theme: "amor" },
  { text: "Não temas, porque eu sou contigo; não te assombres, porque eu sou o teu Deus.", reference: "is 41:10", book: "is", chapter: 41, verse: 10, theme: "coragem" },
  { text: "Toda boa dádiva e todo dom perfeito vêm do alto.", reference: "tg 1:17", book: "tg", chapter: 1, verse: 17, theme: "gratidao" },
  { text: "Ora, a fé é a certeza de coisas que se esperam, a convicção de fatos que se não veem.", reference: "hb 11:1", book: "hb", chapter: 11, verse: 1, theme: "fe" },
  { text: "Sede vós, pois, imitadores de Deus, como filhos amados.", reference: "ef 5:1", book: "ef", chapter: 5, verse: 1, theme: "amor" },
  { text: "A minha paz vos dou; não vo-la dou como o mundo a dá.", reference: "jo 14:27", book: "jo", chapter: 14, verse: 27, theme: "paz" },
  { text: "O temor do Senhor é o princípio da sabedoria.", reference: "pv 9:10", book: "pv", chapter: 9, verse: 10, theme: "sabedoria" },
  { text: "Eis que estou à porta e bato; se alguém ouvir a minha voz e abrir a porta, entrarei em sua casa.", reference: "ap 3:20", book: "ap", chapter: 3, verse: 20, theme: "fe" },
  { text: "Porque Deus amou o mundo de tal maneira que deu o seu Filho unigênito.", reference: "jo 3:16", book: "jo", chapter: 3, verse: 16, theme: "amor" },
  { text: "Não se turbe o vosso coração; credes em Deus, crede também em mim.", reference: "jo 14:1", book: "jo", chapter: 14, verse: 1, theme: "paz" },
  { text: "Ora, sem fé é impossível agradar a Deus.", reference: "hb 11:6", book: "hb", chapter: 11, verse: 6, theme: "fe" },
  { text: "Aquele que não ama não conhece a Deus, pois Deus é amor.", reference: "1jo 4:8", book: "1jo", chapter: 4, verse: 8, theme: "amor" },
  { text: "Tudo tem o seu tempo determinado, e há tempo para todo propósito debaixo do céu.", reference: "ec 3:1", book: "ec", chapter: 3, verse: 1, theme: "sabedoria" },
  { text: "O Senhor é a minha luz e a minha salvação; a quem temerei?", reference: "sl 27:1", book: "sl", chapter: 27, verse: 1, theme: "luz" },
  { text: "Lançai sobre ele toda a vossa ansiedade, porque ele tem cuidado de vós.", reference: "1pe 5:7", book: "1pe", chapter: 5, verse: 7, theme: "conforto" },
  { text: "Mas o fruto do Espírito é amor, alegria, paz, longanimidade, benignidade, bondade, fidelidade.", reference: "gl 5:22", book: "gl", chapter: 5, verse: 22, theme: "paz" },
  { text: "E sabemos que todas as coisas cooperam para o bem daqueles que amam a Deus.", reference: "rm 8:28", book: "rm", chapter: 8, verse: 28, theme: "confianca" },
  { text: "A resposta branda desvia o furor, mas a palavra dura suscita a ira.", reference: "pv 15:1", book: "pv", chapter: 15, verse: 1, theme: "sabedoria" },
  { text: "O choro pode durar uma noite, mas a alegria vem pela manhã.", reference: "sl 30:5", book: "sl", chapter: 30, verse: 5, theme: "esperanca" },
  { text: "Em paz me deito e logo adormeço, porque só tu, Senhor, me fazes habitar em segurança.", reference: "sl 4:8", book: "sl", chapter: 4, verse: 8, theme: "descanso" },
  { text: "Melhor é a paciência do que a arrogância.", reference: "ec 7:8", book: "ec", chapter: 7, verse: 8, theme: "sabedoria" },
  { text: "Porque somos feitura sua, criados em Cristo Jesus para as boas obras.", reference: "ef 2:10", book: "ef", chapter: 2, verse: 10, theme: "confianca" },
  { text: "Criai em mim, ó Deus, um coração puro e renova dentro de mim um espírito reto.", reference: "sl 51:10", book: "sl", chapter: 51, verse: 10, theme: "oracao" },
  { text: "Alegrai-vos sempre no Senhor; outra vez digo: alegrai-vos.", reference: "fp 4:4", book: "fp", chapter: 4, verse: 4, theme: "alegria" },
  { text: "O coração alegre aformoseia o rosto.", reference: "pv 15:13", book: "pv", chapter: 15, verse: 13, theme: "alegria" },
  { text: "Grande paz têm os que amam a tua lei, e para eles não há tropeço.", reference: "sl 119:165", book: "sl", chapter: 119, verse: 165, theme: "paz" },
  { text: "Quem é lento para se irar é grande em entendimento.", reference: "pv 14:29", book: "pv", chapter: 14, verse: 29, theme: "sabedoria" },
  { text: "Alegrem-se os céus e regozije-se a terra!", reference: "sl 96:11", book: "sl", chapter: 96, verse: 11, theme: "alegria" },
  { text: "O nome do Senhor é uma torre forte; o justo corre para ela e está seguro.", reference: "pv 18:10", book: "pv", chapter: 18, verse: 10, theme: "forca" },
  { text: "Os que esperam no Senhor renovam as suas forças.", reference: "is 40:31", book: "is", chapter: 40, verse: 31, theme: "esperanca" },
  { text: "Honra ao Senhor com os teus bens e com as primícias de toda a tua renda.", reference: "pv 3:9", book: "pv", chapter: 3, verse: 9, theme: "gratidao" },
  { text: "A boca do justo profere sabedoria, e a sua língua fala do que é reto.", reference: "sl 37:30", book: "sl", chapter: 37, verse: 30, theme: "sabedoria" },
  { text: "O coração do homem planeja o seu caminho, mas o Senhor lhe dirige os passos.", reference: "pv 16:9", book: "pv", chapter: 16, verse: 9, theme: "confianca" },
  { text: "Eis que a mão do Senhor não está encolhida, para que não possa salvar.", reference: "is 59:1", book: "is", chapter: 59, verse: 1, theme: "fe" },
  { text: "O Senhor é bom, um refúgio em tempos de angústia.", reference: "na 1:7", book: "na", chapter: 1, verse: 7, theme: "conforto" },
  { text: "O caminho do preguiçoso é como se fosse cercado de espinhos, mas a vereda dos retos é aplainada.", reference: "pv 15:19", book: "pv", chapter: 15, verse: 19, theme: "sabedoria" },
  { text: "O segredo do Senhor é para aqueles que o temem.", reference: "sl 25:14", book: "sl", chapter: 25, verse: 14, theme: "fe" },
  { text: "O coração do justo pondera como há de responder, mas a boca dos perversos transborda de maldades.", reference: "pv 15:28", book: "pv", chapter: 15, verse: 28, theme: "sabedoria" },
  { text: "As palavras do sábio são como aguilhões e como pregos bem fixados.", reference: "ec 12:11", book: "ec", chapter: 12, verse: 11, theme: "sabedoria" },
  { text: "O Senhor está perto dos que têm o coração quebrantado.", reference: "sl 34:18", book: "sl", chapter: 34, verse: 18, theme: "conforto" },
  { text: "Melhor é ter um punhado com tranquilidade do que ambas as mãos cheias com fadiga e correr atrás do vento.", reference: "ec 4:6", book: "ec", chapter: 4, verse: 6, theme: "paz" },
  { text: "Quem é piedoso tem misericórdia dos seus animais.", reference: "pv 12:10", book: "pv", chapter: 12, verse: 10, theme: "amor" },
  { text: "A esperança adiada enfraquece o coração, mas o desejo satisfeito é árvore de vida.", reference: "pv 13:12", book: "pv", chapter: 13, verse: 12, theme: "esperanca" },
  { text: "Todas as coisas são puras para os puros, mas para os impuros e incrédulos nada é puro.", reference: "tt 1:15", book: "tt", chapter: 1, verse: 15, theme: "sabedoria" },
  { text: "A fé vem pela pregação, e a pregação pela palavra de Cristo.", reference: "rm 10:17", book: "rm", chapter: 10, verse: 17, theme: "fe" },
  { text: "A nossa salvação está mais perto agora do que quando cremos.", reference: "rm 13:11", book: "rm", chapter: 13, verse: 11, theme: "esperanca" },
  { text: "Revesti-vos do Senhor Jesus Cristo e não vos ocupeis em satisfazer os desejos da carne.", reference: "rm 13:14", book: "rm", chapter: 13, verse: 14, theme: "fe" },
  { text: "Alegrem-se na esperança, sejam pacientes na tribulação, perseverem na oração.", reference: "rm 12:12", book: "rm", chapter: 12, verse: 12, theme: "esperanca" },
  { text: "Não se deixem vencer pelo mal, mas vençam o mal com o bem.", reference: "rm 12:21", book: "rm", chapter: 12, verse: 21, theme: "coragem" },
  { text: "O que semeia para a sua própria carne, da carne colherá corrupção; mas o que semeia para o Espírito, do Espírito colherá vida eterna.", reference: "gl 6:8", book: "gl", chapter: 6, verse: 8, theme: "sabedoria" },
  { text: "O fruto da justiça semeia‑se em paz para os que promovem a paz.", reference: "tg 3:18", book: "tg", chapter: 3, verse: 18, theme: "paz" },
  { text: "Deus se opõe aos soberbos, mas dá graça aos humildes.", reference: "tg 4:6", book: "tg", chapter: 4, verse: 6, theme: "sabedoria" },
  { text: "Aproximem‑se de Deus, e ele se aproximará de vocês.", reference: "tg 4:8", book: "tg", chapter: 4, verse: 8, theme: "oracao" },
  { text: "Todo aquele que é nascido de Deus não vive na prática do pecado.", reference: "1jo 3:9", book: "1jo", chapter: 3, verse: 9, theme: "fe" },
  { text: "Nós amamos porque ele nos amou primeiro.", reference: "1jo 4:19", book: "1jo", chapter: 4, verse: 19, theme: "amor" },
  { text: "Quem crê no Filho tem a vida eterna.", reference: "jo 3:36", book: "jo", chapter: 3, verse: 36, theme: "fe" },
  { text: "Em verdade, em verdade vos digo: quem ouve a minha palavra e crê naquele que me enviou tem a vida eterna.", reference: "jo 5:24", book: "jo", chapter: 5, verse: 24, theme: "fe" },
  { text: "Eu sou a ressurreição e a vida. Quem crê em mim, ainda que morra, viverá.", reference: "jo 11:25", book: "jo", chapter: 11, verse: 25, theme: "fe" },
  { text: "Se vocês permanecerem em mim, e as minhas palavras permanecerem em vocês, pedirão o que quiserem, e lhes será concedido.", reference: "jo 15:7", book: "jo", chapter: 15, verse: 7, theme: "oracao" },
  { text: "Pois o Filho do homem veio buscar e salvar o que estava perdido.", reference: "lc 19:10", book: "lc", chapter: 19, verse: 10, theme: "conforto" },
  { text: "Bem‑aventurados os pobres em espírito, porque deles é o Reino dos céus.", reference: "mt 5:3", book: "mt", chapter: 5, verse: 3, theme: "fe" },
  { text: "Bem‑aventurados os que choram, porque serão consolados.", reference: "mt 5:4", book: "mt", chapter: 5, verse: 4, theme: "conforto" },
  { text: "Bem‑aventurados os mansos, porque herdarão a terra.", reference: "mt 5:5", book: "mt", chapter: 5, verse: 5, theme: "paz" },
  { text: "Bem‑aventurados os que têm fome e sede de justiça, porque serão fartos.", reference: "mt 5:6", book: "mt", chapter: 5, verse: 6, theme: "esperanca" },
  { text: "Bem‑aventurados os misericordiosos, porque alcançarão misericórdia.", reference: "mt 5:7", book: "mt", chapter: 5, verse: 7, theme: "amor" },
  { text: "Bem‑aventurados os puros de coração, porque verão a Deus.", reference: "mt 5:8", book: "mt", chapter: 5, verse: 8, theme: "fe" },
  { text: "Bem‑aventurados os pacificadores, porque serão chamados filhos de Deus.", reference: "mt 5:9", book: "mt", chapter: 5, verse: 9, theme: "paz" },
  { text: "Bem‑aventurados os perseguidos por causa da justiça, porque deles é o Reino dos céus.", reference: "mt 5:10", book: "mt", chapter: 5, verse: 10, theme: "coragem" },
  { text: "Vós sois o sal da terra; e se o sal se tornar insípido, com que se há de salgar?", reference: "mt 5:13", book: "mt", chapter: 5, verse: 13, theme: "sabedoria" },
  { text: "Vós sois a luz do mundo. Não se pode esconder uma cidade edificada sobre um monte.", reference: "mt 5:14", book: "mt", chapter: 5, verse: 14, theme: "luz" },
  { text: "Assim brilhe também a vossa luz diante dos homens, para que vejam as vossas boas obras e glorifiquem a vosso Pai que está nos céus.", reference: "mt 5:16", book: "mt", chapter: 5, verse: 16, theme: "luz" },
  { text: "Não julgueis, para que não sejais julgados.", reference: "mt 7:1", book: "mt", chapter: 7, verse: 1, theme: "sabedoria" },
  { text: "Pedi, e dar‑se‑vos‑á; buscai, e achareis; batei, e abrir‑se‑vos‑á.", reference: "mt 7:7", book: "mt", chapter: 7, verse: 7, theme: "oracao" },
  { text: "Tudo o que quereis que os homens vos façam, fazei‑lho também vós a eles.", reference: "mt 7:12", book: "mt", chapter: 7, verse: 12, theme: "amor" },
  { text: "Nem só de pão viverá o homem, mas de toda palavra que sai da boca de Deus.", reference: "mt 4:4", book: "mt", chapter: 4, verse: 4, theme: "fe" },
  { text: "O reino de Deus não é comida nem bebida, mas justiça, paz e alegria no Espírito Santo.", reference: "rm 14:17", book: "rm", chapter: 14, verse: 17, theme: "alegria" },
  { text: "O Deus de esperança vos encha de toda alegria e paz na vossa fé.", reference: "rm 15:13", book: "rm", chapter: 15, verse: 13, theme: "esperanca" },
  { text: "Aquele que começou a boa obra em vós a aperfeiçoará até o dia de Cristo Jesus.", reference: "fp 1:6", book: "fp", chapter: 1, verse: 6, theme: "confianca" },
  { text: "Nada façais por contenda ou por vanglória, mas por humildade, cada um considere os outros superiores a si mesmo.", reference: "fp 2:3", book: "fp", chapter: 2, verse: 3, theme: "sabedoria" },
  { text: "Tende em vós o mesmo sentimento que houve também em Cristo Jesus.", reference: "fp 2:5", book: "fp", chapter: 2, verse: 5, theme: "sabedoria" },
  { text: "O Deus de toda a graça vos aperfeiçoará, confirmará, fortificará e fundamentará.", reference: "1pe 5:10", book: "1pe", chapter: 5, verse: 10, theme: "confianca" },

  // ===== Ampliação: mais variedade e temas de esperança, coragem, conforto, gratidão e cura =====
  { text: "Levanto os olhos para os montes: de onde me vem o socorro? O meu socorro vem do Senhor.", reference: "sl 121:1-2", book: "sl", chapter: 121, verse: 1, theme: "confianca" },
  { text: "Aquele que habita no esconderijo do Altíssimo, à sombra do Onipotente descansará.", reference: "sl 91:1", book: "sl", chapter: 91, verse: 1, theme: "descanso" },
  { text: "Tu conservarás em paz aquele cuja mente está firme em ti, porque em ti confia.", reference: "is 26:3", book: "is", chapter: 26, verse: 3, theme: "paz" },
  { text: "Quando passares pelas águas, estarei contigo; e quando pelos rios, eles não te submergirão.", reference: "is 43:2", book: "is", chapter: 43, verse: 2, theme: "coragem" },
  { text: "Porque eu bem sei os pensamentos que tenho a vosso respeito, pensamentos de paz e não de mal, para vos dar o fim que esperais.", reference: "jr 29:11", book: "jr", chapter: 29, verse: 11, theme: "esperanca" },
  { text: "Não te mandei eu? Sê forte e corajoso; não temas, nem te espantes, porque o Senhor teu Deus é contigo.", reference: "js 1:9", book: "js", chapter: 1, verse: 9, theme: "coragem" },
  { text: "Sê forte e corajoso; não temas, nem te espantes diante deles, porque o Senhor teu Deus é aquele que vai contigo.", reference: "dt 31:6", book: "dt", chapter: 31, verse: 6, theme: "coragem" },
  { text: "Se Deus é por nós, quem será contra nós?", reference: "rm 8:31", book: "rm", chapter: 8, verse: 31, theme: "confianca" },
  { text: "Nem a morte, nem a vida... poderá separar-nos do amor de Deus, que está em Cristo Jesus nosso Senhor.", reference: "rm 8:38-39", book: "rm", chapter: 8, verse: 38, theme: "amor" },
  { text: "A minha graça te basta, porque o meu poder se aperfeiçoa na fraqueza.", reference: "2co 12:9", book: "2co", chapter: 12, verse: 9, theme: "forca" },
  { text: "Se alguém está em Cristo, nova criatura é; as coisas velhas já passaram; eis que tudo se fez novo.", reference: "2co 5:17", book: "2co", chapter: 5, verse: 17, theme: "esperanca" },
  { text: "Fortalecei-vos no Senhor e na força do seu poder.", reference: "ef 6:10", book: "ef", chapter: 6, verse: 10, theme: "forca" },
  { text: "Não andeis ansiosos de coisa alguma; e a paz de Deus, que excede todo o entendimento, guardará os vossos corações.", reference: "fp 4:6-7", book: "fp", chapter: 4, verse: 6, theme: "paz" },
  { text: "O meu Deus suprirá todas as vossas necessidades, segundo as suas riquezas na glória em Cristo Jesus.", reference: "fp 4:19", book: "fp", chapter: 4, verse: 19, theme: "confianca" },
  { text: "Tudo o que fizerdes, fazei-o de todo o coração, como para o Senhor, e não para os homens.", reference: "cl 3:23", book: "cl", chapter: 3, verse: 23, theme: "sabedoria" },
  { text: "Tende por motivo de toda a alegria o passardes por várias provações, sabendo que a prova da vossa fé produz perseverança.", reference: "tg 1:2-4", book: "tg", chapter: 1, verse: 2, theme: "superacao" },
  { text: "Deleita-te também no Senhor, e ele te concederá o que deseja o teu coração.", reference: "sl 37:4-5", book: "sl", chapter: 37, verse: 4, theme: "esperanca" },
  { text: "Lança sobre o Senhor o teu cuidado, e ele te susterá; jamais permitirá que o justo seja abalado.", reference: "sl 55:22", book: "sl", chapter: 55, verse: 22, theme: "conforto" },
  { text: "Buscai primeiro o Reino de Deus e a sua justiça, e todas essas coisas vos serão acrescentadas.", reference: "mt 6:33", book: "mt", chapter: 6, verse: 33, theme: "confianca" },
  { text: "E eis que estou convosco todos os dias, até a consumação dos séculos.", reference: "mt 28:20", book: "mt", chapter: 28, verse: 20, theme: "conforto" },
  { text: "Eu vim para que tenham vida, e a tenham em abundância.", reference: "jo 10:10", book: "jo", chapter: 10, verse: 10, theme: "esperanca" },
  { text: "No mundo tereis aflições, mas tende bom ânimo; eu venci o mundo.", reference: "jo 16:33", book: "jo", chapter: 16, verse: 33, theme: "coragem" },
  { text: "Confia no Senhor de todo o teu coração e não te estribes no teu próprio entendimento.", reference: "pv 3:5-6", book: "pv", chapter: 3, verse: 5, theme: "confianca" },
  { text: "As misericórdias do Senhor são a causa de não sermos consumidos; renovam-se cada manhã.", reference: "lm 3:22-23", book: "lm", chapter: 3, verse: 22, theme: "esperanca" },
  { text: "O Senhor Deus é a minha força; ele faz os meus pés como os da corça e me faz andar sobre as minhas alturas.", reference: "hc 3:19", book: "hc", chapter: 3, verse: 19, theme: "forca" },
  { text: "O Senhor teu Deus está no meio de ti, poderoso para te salvar; ele se alegra muito por tua causa.", reference: "sf 3:17", book: "sf", chapter: 3, verse: 17, theme: "amor" },
  { text: "Porque Deus não nos deu espírito de covardia, mas de poder, de amor e de moderação.", reference: "2tm 1:7", book: "2tm", chapter: 1, verse: 7, theme: "coragem" },
  { text: "Nunca te deixarei, nunca te abandonarei; o Senhor é o meu ajudador, não temerei.", reference: "hb 13:5-6", book: "hb", chapter: 13, verse: 5, theme: "confianca" },
  { text: "Não veio sobre vós tentação que não fosse humana; Deus é fiel e não deixará que sejais tentados além do que podeis suportar.", reference: "1co 10:13", book: "1co", chapter: 10, verse: 13, theme: "superacao" },
  { text: "E não nos cansemos de fazer o bem, pois no tempo próprio ceifaremos, se não desfalecermos.", reference: "gl 6:9", book: "gl", chapter: 6, verse: 9, theme: "superacao" },
  { text: "Tu me farás conhecer a vereda da vida; na tua presença há fartura de alegria.", reference: "sl 16:11", book: "sl", chapter: 16, verse: 11, theme: "alegria" },
  { text: "Provai e vede que o Senhor é bom; bem-aventurado o homem que nele confia.", reference: "sl 34:8", book: "sl", chapter: 34, verse: 8, theme: "confianca" },
  { text: "A minha carne e o meu coração desfalecem, mas Deus é a fortaleza do meu coração e a minha herança para sempre.", reference: "sl 73:26", book: "sl", chapter: 73, verse: 26, theme: "forca" },
  { text: "Este é o dia que o Senhor fez; regozijemo-nos e alegremo-nos nele.", reference: "sl 118:24", book: "sl", chapter: 118, verse: 24, theme: "alegria" },
  { text: "O Senhor cumprirá o seu propósito em mim; a tua benignidade, Senhor, dura para sempre.", reference: "sl 138:8", book: "sl", chapter: 138, verse: 8, theme: "confianca" },
  { text: "Sara os quebrantados de coração e lhes ata as suas feridas.", reference: "sl 147:3", book: "sl", chapter: 147, verse: 3, theme: "cura" },
  { text: "Os que esperam no Senhor renovam as suas forças; sobem com asas como águias.", reference: "is 40:31b", book: "is", chapter: 40, verse: 31, theme: "esperanca" },
  { text: "Não temas, porque eu sou contigo; sim, eu te ajudo e te sustento com a destra da minha justiça.", reference: "is 41:13", book: "is", chapter: 41, verse: 13, theme: "coragem" },
  { text: "Porque os montes se retirarão, mas a minha benignidade não se apartará de ti, diz o Senhor, que se compadece de ti.", reference: "is 54:10", book: "is", chapter: 54, verse: 10, theme: "conforto" },
  { text: "Ainda que caia, não ficarei prostrado, porque o Senhor sustém a minha mão.", reference: "mq 7:8", book: "mq", chapter: 7, verse: 8, theme: "superacao" },
  { text: "Olhai para as aves do céu: não semeiam, não colhem e vosso Pai celestial as sustenta.", reference: "mt 6:26", book: "mt", chapter: 6, verse: 26, theme: "confianca" },
  { text: "Vinde a mim, tomai sobre vós o meu jugo, pois é suave e o meu fardo é leve.", reference: "mt 11:29-30", book: "mt", chapter: 11, verse: 29, theme: "descanso" },
  { text: "Porque para Deus nada é impossível.", reference: "lc 1:37", book: "lc", chapter: 1, verse: 37, theme: "fe" },
  { text: "A luz resplandece nas trevas, e as trevas não prevaleceram contra ela.", reference: "jo 1:5", book: "jo", chapter: 1, verse: 5, theme: "luz" },
  { text: "Eu sou a videira, vós, os ramos; quem permanece em mim, e eu, nele, esse dá muito fruto.", reference: "jo 15:5", book: "jo", chapter: 15, verse: 5, theme: "confianca" },
  { text: "E o sofrimento produz perseverança; a perseverança, experiência; e a experiência, esperança.", reference: "rm 5:3-4", book: "rm", chapter: 5, verse: 3, theme: "superacao" },
  { text: "Agora, pois, permanecem a fé, a esperança e o amor, estes três; porém o maior destes é o amor.", reference: "1co 13:13", book: "1co", chapter: 13, verse: 13, theme: "amor" },
  { text: "Não desfalecemos; embora o nosso homem exterior se corrompa, o interior se renova de dia em dia.", reference: "2co 4:16", book: "2co", chapter: 4, verse: 16, theme: "superacao" },
  { text: "Poderoso é Deus para fazer abundar sobre vós toda a graça, a fim de que, tendo sempre toda suficiência, abundeis em toda boa obra.", reference: "2co 9:8", book: "2co", chapter: 9, verse: 8, theme: "gratidao" },
  { text: "Já estou crucificado com Cristo; e vivo, não mais eu, mas Cristo vive em mim.", reference: "gl 2:20", book: "gl", chapter: 2, verse: 20, theme: "fe" },
  { text: "Pela graça sois salvos, mediante a fé; e isto não vem de vós, é dom de Deus.", reference: "ef 2:8", book: "ef", chapter: 2, verse: 8, theme: "fe" },
  { text: "Àquele que é poderoso para fazer infinitamente mais do que tudo quanto pedimos ou pensamos, seja glória.", reference: "ef 3:20", book: "ef", chapter: 3, verse: 20, theme: "confianca" },
  { text: "Tudo o que é verdadeiro, tudo o que é honesto, tudo o que é amável, nisto pensai.", reference: "fp 4:8", book: "fp", chapter: 4, verse: 8, theme: "sabedoria" },
  { text: "E a paz de Cristo domine em vossos corações, à qual também fostes chamados em um corpo; e sede agradecidos.", reference: "cl 3:15", book: "cl", chapter: 3, verse: 15, theme: "paz" },
  { text: "Regozijai-vos sempre, orai sem cessar, em tudo dai graças.", reference: "1ts 5:16-18", book: "1ts", chapter: 5, verse: 16, theme: "gratidao" },
  { text: "Mas fiel é o Senhor, que vos confirmará e guardará do maligno.", reference: "2ts 3:3", book: "2ts", chapter: 3, verse: 3, theme: "confianca" },
  { text: "Cheguemos, pois, com confiança ao trono da graça, para que possamos alcançar misericórdia e achar graça em tempo oportuno.", reference: "hb 4:16", book: "hb", chapter: 4, verse: 16, theme: "oracao" },
  { text: "Corramos com perseverança a corrida que nos está proposta, olhando para Jesus, autor e consumador da fé.", reference: "hb 12:1", book: "hb", chapter: 12, verse: 1, theme: "superacao" },
  { text: "Humilhai-vos perante o Senhor, e ele vos exaltará.", reference: "tg 4:10", book: "tg", chapter: 4, verse: 10, theme: "sabedoria" },
  { text: "Bendito o Deus e Pai, que, segundo a sua muita misericórdia, nos gerou de novo para uma viva esperança.", reference: "1pe 1:3", book: "1pe", chapter: 1, verse: 3, theme: "esperanca" },
  { text: "Vós sois a geração eleita, o sacerdócio real, o povo adquirido, para anunciardes as virtudes daquele que vos chamou.", reference: "1pe 2:9", book: "1pe", chapter: 2, verse: 9, theme: "gratidao" },
  { text: "Se confessarmos os nossos pecados, ele é fiel e justo para nos perdoar os pecados e nos purificar de toda injustiça.", reference: "1jo 1:9", book: "1jo", chapter: 1, verse: 9, theme: "perdao" },
  { text: "Porque todo o que é nascido de Deus vence o mundo; e esta é a vitória que vence o mundo: a nossa fé.", reference: "1jo 5:4", book: "1jo", chapter: 5, verse: 4, theme: "superacao" },
  { text: "Enxugará Deus de seus olhos toda lágrima; e não haverá mais morte, nem pranto, nem lamento, nem dor.", reference: "ap 21:4", book: "ap", chapter: 21, verse: 4, theme: "conforto" }
];
