export const FALLBACK_VERSES = [
  { text: "O Senhor é o meu pastor; nada me faltará.", reference: "sl 23:1", book: "sl", chapter: 23, verse: 1 },
  { text: "Deus é amor; e aquele que permanece em amor permanece em Deus, e Deus nele.", reference: "1jo 4:16", book: "1jo", chapter: 4, verse: 16 },
  { text: "Tudo posso naquele que me fortalece.", reference: "fp 4:13", book: "fp", chapter: 4, verse: 13 },
  { text: "Buscai ao Senhor enquanto se pode achar, invocai-o enquanto está perto.", reference: "is 55:6", book: "is", chapter: 55, verse: 6 },
  { text: "Deus é o nosso refúgio e fortaleza, socorro bem presente nas tribulações.", reference: "sl 46:1", book: "sl", chapter: 46, verse: 1 },
  { text: "A alegria do Senhor é a vossa força.", reference: "ne 8:10", book: "ne", chapter: 8, verse: 10 },
  { text: "E conhecereis a verdade, e a verdade vos libertará.", reference: "jo 8:32", book: "jo", chapter: 8, verse: 32 },
  { text: "Respondeu Jesus: Eu sou o caminho, e a verdade, e a vida.", reference: "jo 14:6", book: "jo", chapter: 14, verse: 6 },
  { text: "Vinde a mim, todos os que estais cansados e sobrecarregados, e eu vos aliviarei.", reference: "mt 11:28", book: "mt", chapter: 11, verse: 28 },
  { text: "O amor é paciente, é benigno; o amor não arde em ciúmes, não se ufana, não se ensoberbece.", reference: "1co 13:4", book: "1co", chapter: 13, verse: 4 },
  { text: "Não temas, porque eu sou contigo; não te assombres, porque eu sou o teu Deus.", reference: "is 41:10", book: "is", chapter: 41, verse: 10 },
  { text: "Toda boa dádiva e todo dom perfeito vêm do alto.", reference: "tg 1:17", book: "tg", chapter: 1, verse: 17 },
  { text: "Ora, a fé é a certeza de coisas que se esperam, a convicção de fatos que se não veem.", reference: "hb 11:1", book: "hb", chapter: 11, verse: 1 },
  { text: "Sede vós, pois, imitadores de Deus, como filhos amados.", reference: "ef 5:1", book: "ef", chapter: 5, verse: 1 },
  { text: "A minha paz vos dou; não vo-la dou como o mundo a dá.", reference: "jo 14:27", book: "jo", chapter: 14, verse: 27 },
  { text: "O temor do Senhor é o princípio da sabedoria.", reference: "pv 9:10", book: "pv", chapter: 9, verse: 10 },
  { text: "Eis que estou à porta e bato; se alguém ouvir a minha voz e abrir a porta, entrarei em sua casa.", reference: "ap 3:20", book: "ap", chapter: 3, verse: 20 },
  { text: "Porque Deus amou o mundo de tal maneira que deu o seu Filho unigênito.", reference: "jo 3:16", book: "jo", chapter: 3, verse: 16 },
  { text: "Não se turbe o vosso coração; credes em Deus, crede também em mim.", reference: "jo 14:1", book: "jo", chapter: 14, verse: 1 },
  { text: "Ora, sem fé é impossível agradar a Deus.", reference: "hb 11:6", book: "hb", chapter: 11, verse: 6 },
  { text: "Aquele que não ama não conhece a Deus, pois Deus é amor.", reference: "1jo 4:8", book: "1jo", chapter: 4, verse: 8 },
  { text: "Tudo tem o seu tempo determinado, e há tempo para todo propósito debaixo do céu.", reference: "ec 3:1", book: "ec", chapter: 3, verse: 1 },
  { text: "O Senhor é a minha luz e a minha salvação; a quem temerei?", reference: "sl 27:1", book: "sl", chapter: 27, verse: 1 },
  { text: "Lançai sobre ele toda a vossa ansiedade, porque ele tem cuidado de vós.", reference: "1pe 5:7", book: "1pe", chapter: 5, verse: 7 },
  { text: "Mas o fruto do Espírito é amor, alegria, paz, longanimidade, benignidade, bondade, fidelidade.", reference: "gl 5:22", book: "gl", chapter: 5, verse: 22 },
  { text: "E sabemos que todas as coisas cooperam para o bem daqueles que amam a Deus.", reference: "rm 8:28", book: "rm", chapter: 8, verse: 28 },
  { text: "A resposta branda desvia o furor, mas a palavra dura suscita a ira.", reference: "pv 15:1", book: "pv", chapter: 15, verse: 1 },
  { text: "O choro pode durar uma noite, mas a alegria vem pela manhã.", reference: "sl 30:5", book: "sl", chapter: 30, verse: 5 },
  { text: "Em paz me deito e logo adormeço, porque só tu, Senhor, me fazes habitar em segurança.", reference: "sl 4:8", book: "sl", chapter: 4, verse: 8 },
  { text: "Melhor é a paciência do que a arrogância.", reference: "ec 7:8", book: "ec", chapter: 7, verse: 8 },
  { text: "Porque somos feitura sua, criados em Cristo Jesus para as boas obras.", reference: "ef 2:10", book: "ef", chapter: 2, verse: 10 },
  { text: "Criai em mim, ó Deus, um coração puro e renova dentro de mim um espírito reto.", reference: "sl 51:10", book: "sl", chapter: 51, verse: 10 },
  { text: "Alegrai-vos sempre no Senhor; outra vez digo: alegrai-vos.", reference: "fp 4:4", book: "fp", chapter: 4, verse: 4 },
  { text: "O coração alegre aformoseia o rosto.", reference: "pv 15:13", book: "pv", chapter: 15, verse: 13 },
  { text: "Grande paz têm os que amam a tua lei, e para eles não há tropeço.", reference: "sl 119:165", book: "sl", chapter: 119, verse: 165 },
  { text: "Quem é lento para se irar é grande em entendimento.", reference: "pv 14:29", book: "pv", chapter: 14, verse: 29 },
  { text: "Alegrem-se os céus e regozije-se a terra!", reference: "sl 96:11", book: "sl", chapter: 96, verse: 11 },
  { text: "O nome do Senhor é uma torre forte; o justo corre para ela e está seguro.", reference: "pv 18:10", book: "pv", chapter: 18, verse: 10 },
  { text: "Os que esperam no Senhor renovam as suas forças.", reference: "is 40:31", book: "is", chapter: 40, verse: 31 },
  { text: "Honra ao Senhor com os teus bens e com as primícias de toda a tua renda.", reference: "pv 3:9", book: "pv", chapter: 3, verse: 9 },
  { text: "A boca do justo profere sabedoria, e a sua língua fala do que é reto.", reference: "sl 37:30", book: "sl", chapter: 37, verse: 30 },
  { text: "O coração do homem planeja o seu caminho, mas o Senhor lhe dirige os passos.", reference: "pv 16:9", book: "pv", chapter: 16, verse: 9 },
  { text: "Eis que a mão do Senhor não está encolhida, para que não possa salvar.", reference: "is 59:1", book: "is", chapter: 59, verse: 1 },
  { text: "O Senhor é bom, um refúgio em tempos de angústia.", reference: "na 1:7", book: "na", chapter: 1, verse: 7 },
  { text: "O caminho do preguiçoso é como se fosse cercado de espinhos, mas a vereda dos upright é aplainada.", reference: "pv 15:19", book: "pv", chapter: 15, verse: 19 },
  { text: "O segredo do Senhor é para aqueles que o temem.", reference: "sl 25:14", book: "sl", chapter: 25, verse: 14 },
  { text: "O coração do justo pondera como há de responder, mas a boca dos perversos transborda de maldades.", reference: "pv 15:28", book: "pv", chapter: 15, verse: 28 },
  { text: "As palavras do sábio são como aguilhões e como pregos bem fixados.", reference: "ec 12:11", book: "ec", chapter: 12, verse: 11 },
  { text: "O Senhor está perto dos que têm o coração quebrantado.", reference: "sl 34:18", book: "sl", chapter: 34, verse: 18 },
  { text: "Melhor é ter um punhado com tranquilidade do que ambas as mãos cheias com fadiga e correr atrás do vento.", reference: "ec 4:6", book: "ec", chapter: 4, verse: 6 },
  { text: "Quem é piedoso tem misericórdia dos seus animais.", reference: "pv 12:10", book: "pv", chapter: 12, verse: 10 },
  { text: "A esperança adiada enfraquece o coração, mas o desejo satisfeito é árvore de vida.", reference: "pv 13:12", book: "pv", chapter: 13, verse: 12 },
  { text: "Todas as coisas são puras para os puros, mas para os impuros e incrédulos nada é puro.", reference: "tt 1:15", book: "tt", chapter: 1, verse: 15 },
  { text: "A fé vem pela pregação, e a pregação pela palavra de Cristo.", reference: "rm 10:17", book: "rm", chapter: 10, verse: 17 },
  { text: "A nossa salvação está mais perto agora do que quando cremos.", reference: "rm 13:11", book: "rm", chapter: 13, verse: 11 },
  { text: "Revesti-vos do Senhor Jesus Cristo e não vos ocupeis em satisfazer os desejos da carne.", reference: "rm 13:14", book: "rm", chapter: 13, verse: 14 },
  { text: "Alegrem-se na esperança, sejam pacientes na tribulação, perseverem na oração.", reference: "rm 12:12", book: "rm", chapter: 12, verse: 12 },
  { text: "Não se deixem vencer pelo mal, mas vençam o mal com o bem.", reference: "rm 12:21", book: "rm", chapter: 12, verse: 21 },
  { text: "O que semeia para a sua própria carne, da carne colherá corrupção; mas o que semeia para o Espírito, do Espírito colherá vida eterna.", reference: "gl 6:8", book: "gl", chapter: 6, verse: 8 },
  { text: "O fruto da justiça semeia‑se em paz para os que promovem a paz.", reference: "tg 3:18", book: "tg", chapter: 3, verse: 18 },
  { text: "Deus se opõe aos soberbos, mas dá graça aos humildes.", reference: "tg 4:6", book: "tg", chapter: 4, verse: 6 },
  { text: "Aproximem‑se de Deus, e ele se aproximará de vocês.", reference: "tg 4:8", book: "tg", chapter: 4, verse: 8 },
  { text: "Todo aquele que é nascido de Deus não vive na prática do pecado.", reference: "1jo 3:9", book: "1jo", chapter: 3, verse: 9 },
  { text: "Nós amamos porque ele nos amou primeiro.", reference: "1jo 4:19", book: "1jo", chapter: 4, verse: 19 },
  { text: "Quem crê no Filho tem a vida eterna.", reference: "jo 3:36", book: "jo", chapter: 3, verse: 36 },
  { text: "Em verdade, em verdade vos digo: quem ouve a minha palavra e crê naquele que me enviou tem a vida eterna.", reference: "jo 5:24", book: "jo", chapter: 5, verse: 24 },
  { text: "Eu sou a ressurreição e a vida. Quem crê em mim, ainda que morra, viverá.", reference: "jo 11:25", book: "jo", chapter: 11, verse: 25 },
  { text: "Se vocês permanecerem em mim, e as minhas palavras permanecerem em vocês, pedirão o que quiserem, e lhes será concedido.", reference: "jo 15:7", book: "jo", chapter: 15, verse: 7 },
  { text: "Pois o Filho do homem veio buscar e salvar o que estava perdido.", reference: "lc 19:10", book: "lc", chapter: 19, verse: 10 },
  { text: "Bem‑aventurados os pobres em espírito, porque deles é o Reino dos céus.", reference: "mt 5:3", book: "mt", chapter: 5, verse: 3 },
  { text: "Bem‑aventurados os que choram, porque serão consolados.", reference: "mt 5:4", book: "mt", chapter: 5, verse: 4 },
  { text: "Bem‑aventurados os mansos, porque herdarão a terra.", reference: "mt 5:5", book: "mt", chapter: 5, verse: 5 },
  { text: "Bem‑aventurados os que têm fome e sede de justiça, porque serão fartos.", reference: "mt 5:6", book: "mt", chapter: 5, verse: 6 },
  { text: "Bem‑aventurados os misericordiosos, porque alcançarão misericórdia.", reference: "mt 5:7", book: "mt", chapter: 5, verse: 7 },
  { text: "Bem‑aventurados os puros de coração, porque verão a Deus.", reference: "mt 5:8", book: "mt", chapter: 5, verse: 8 },
  { text: "Bem‑aventurados os pacificadores, porque serão chamados filhos de Deus.", reference: "mt 5:9", book: "mt", chapter: 5, verse: 9 },
  { text: "Bem‑aventurados os perseguidos por causa da justiça, porque deles é o Reino dos céus.", reference: "mt 5:10", book: "mt", chapter: 5, verse: 10 },
  { text: "Vós sois o sal da terra; e se o sal se tornar insípido, com que se há de salgar?", reference: "mt 5:13", book: "mt", chapter: 5, verse: 13 },
  { text: "Vós sois a luz do mundo. Não se pode esconder uma cidade edificada sobre um monte.", reference: "mt 5:14", book: "mt", chapter: 5, verse: 14 },
  { text: "Assim brilhe também a vossa luz diante dos homens, para que vejam as vossas boas obras e glorifiquem a vosso Pai que está nos céus.", reference: "mt 5:16", book: "mt", chapter: 5, verse: 16 },
  { text: "Não julgueis, para que não sejais julgados.", reference: "mt 7:1", book: "mt", chapter: 7, verse: 1 },
  { text: "Pedi, e dar‑se‑vos‑á; buscai, e achareis; batei, e abrir‑se‑vos‑á.", reference: "mt 7:7", book: "mt", chapter: 7, verse: 7 },
  { text: "Tudo o que quereis que os homens vos façam, fazei‑lho também vós a eles.", reference: "mt 7:12", book: "mt", chapter: 7, verse: 12 },
  { text: "Nem só de pão viverá o homem, mas de toda palavra que sai da boca de Deus.", reference: "mt 4:4", book: "mt", chapter: 4, verse: 4 },
  { text: "O reino de Deus não é comida nem bebida, mas justiça, paz e alegria no Espírito Santo.", reference: "rm 14:17", book: "rm", chapter: 14, verse: 17 },
  { text: "O Deus de esperança vos encha de toda alegria e paz na vossa fé.", reference: "rm 15:13", book: "rm", chapter: 15, verse: 13 },
  { text: "Aquele que começou a boa obra em vós a aperfeiçoará até o dia de Cristo Jesus.", reference: "fp 1:6", book: "fp", chapter: 1, verse: 6 },
  { text: "Nada façais por contenda ou por vanglória, mas por humildade, cada um considere os outros superiores a si mesmo.", reference: "fp 2:3", book: "fp", chapter: 2, verse: 3 },
  { text: "Tende em vós o mesmo sentimento que houve também em Cristo Jesus.", reference: "fp 2:5", book: "fp", chapter: 2, verse: 5 },
  { text: "O Deus de toda a graça vos aperfeiçoará, confirmará, fortificará e fundamentará.", reference: "1pe 5:10", book: "1pe", chapter: 5, verse: 10 }
];
